### ISSUE TITLE
v2.3.2 does not work

### ISSUE THREAD

**Issue by lcarsos** [allure-framework/allure-npm#10]
I cannot view reports generated with 2.3.2, it works when I version pin back to 2.2.1

[console.log.txt](https://github.com/allure-framework/allure-npm/files/1209146/console.log.txt)

**Comment by baev** [comment]
Yeah, 2.3.2 is broken (thanks to backbone.marionette v3.4.0 release) 

2.3.3 fixes the problem, gonna be published to npm within a hour

**Comment by lcarsos** [comment]
Excellent! Thanks for being on top of it.

**Comment by lcarsos** [comment]
You could leave this open so there's any indication on the npm page that there's a problem with the latest version.

**Comment by fobos** [comment]
@baev it is still not published on npm

**Comment by baev** [comment]
sorry for the delay, published right now
