### ISSUE TITLE
allure version 2.0.0 onwards does not generate full spec test report

### ISSUE THREAD

**Issue by amiya-pattnaik** [allure-framework/allure-npm#11]
Hi,
I am using allure-report to generate my test report. In my framework we are using `wdio-allure-report` package. Automation script are running parallel on multiple browser like, Safari, Chrome, Firefox etc.  Till the allure-commandline version 1.5.0 it generate the consolidated report for all browser like - capabilities: chrome, FF etc. Lets say I have 10 test cases running on three browser simultaneously, I am getting of 30 test case result as consolidated  one till the allure-commandline version 1.5.0. in the allure index.html page. But  after upgrading to the allure-commandline@2.0.0 and till the 2.3.3, it does not generate  the consolidated reports of all browser where as it only shows one browser execution report which contains results of only 10 test cases instead of 30 test cases.

Also another issue is .. in order to generate the allure report, the allure-commandline version 1.5.0 and above  requires to install allure-js-commons": 1.2.1 version. 

Could you please check and resolve this issue.

**Comment by ttobis** [comment]
Any update on this? I have the same problem.

**Comment by baev** [comment]
Thats is a common issue with test environments. Such parameters are not included to `historyId` (such attribute used for history & retries). You can find missed tests at retries tab. 

As workaround you need to provide such variables as parameters to the report (by adding them to each test). BTW not sure is it possible via wdio reporter api.

We are going to solve the problem introducing environments feature https://github.com/allure-framework/allure2/issues/130

**Comment by auto-qa-git** [comment]
@baev Hi, I want to ask if this issue was resolved. I am running e2e tests parallel on multiple browsers but the generated allure reports do not specify the environment. I think I see the report of only 1 browser and I cannot tell which because it doesn't mention it. 
Can you please help? Thank you.
