### ISSUE TITLE
Cucumber step order in allure-report

### ISSUE THREAD

**Issue by IlgizVafin** [allure-framework/allure-npm#14]
I upgrated allure-commandline to v2.3.4 with execution order improvement. But the cucumber step order isn't correct.

Please, look at the screenshots: 
1. *.feature
![image](https://user-images.githubusercontent.com/7014659/29919178-adab04a6-8e61-11e7-88c0-8ba36ff93d3b.png)

2. allure-report
![image](https://user-images.githubusercontent.com/7014659/29919132-86e86c8c-8e61-11e7-953b-c3be9bf77e27.png)

Demo project - https://github.com/IlgizVafin/webdriverio-demo-project2

**Comment by just-boris** [comment]
Could you please re-create the issue in the main repository: https://github.com/allure-framework/allure2

Allure-npm repo contains only few script helpers to manage releases to NPM, but has nothing to do with Allure logic itself. And also I am not sure, that other core team members receive notifications from this repo.

**Comment by IlgizVafin** [comment]
@just-boris done. https://github.com/allure-framework/allure2/issues/587

**Comment by eliranshani** [comment]
When are you planning on releasing this fix along with the latest Allure version ?
@just-boris

**Comment by anilkoithara** [comment]
![image](https://user-images.githubusercontent.com/32519638/46094050-dbc00700-c1b0-11e8-9c9f-0ec4baf299dd.png)

I am still having the same issue, all my dependency are up to date and In my scenario I am using scenario outline. Look like its generating the steps in alphabetical order.
