### ISSUE TITLE
wiki.qatools.re not reachable

### ISSUE THREAD

**Issue by johnmondeen** [allure-framework/allure-npm#18]
The website http://wiki.qatools.ru/display/AL/Allure+Commandline won't load.
It's been giving me a 504 Gateway Timeout - Error since last week.

---
![image](https://user-images.githubusercontent.com/33839129/33436074-4f09ea32-d5e4-11e7-9b52-6f1bdb93fc36.png)

---

Please make your wiki reachable!

**Comment by baev** [comment]
all the docs moved to https://docs.qameta.io/allure/2.0 . 

PS README updated
