### ISSUE TITLE
How to pass --clean args to commond-line

### ISSUE THREAD

**Issue by espekkaya** [allure-framework/allure-npm#24]
Hello,
I want to generete allure-report via cli. But I haven't figured passing clean arg out. 

Whatever I have tried, I have got an error.

Thank you in advanced.

Here is my code

conf.js

`    reporterOptions: {
        allure: {
            outputDir: 'Allure/allure-result'
        }
    },`

CommonUtils.js

`        const reportResultPath = config.reporterOptions.allure.outputDir;
        const reportPath = config.reportPath;

        // returns ChildProcess instance
        const generation = allure(['generate', reportResultPath]);

        generation.on('exit', (exitCode) => {
            console.log('Generation is finished with code:', exitCode);

            if(exitCode === 1)
                reject(exitCode);
            else
            {
                // allure(['open', config.reportPath]);
                fullfill(exitCode);
            }
        });`

**Comment by haleagar** [comment]
const generation = allure(['generate', reportResultPath, '--clean']);
