### ISSUE TITLE
bad documentation

### ISSUE THREAD

**Issue by akey1982** [allure-framework/allure-npm#27]
sorry but your documentation about how to use this is very bad

**Comment by zachlysobey** [comment]
not very diplomatic, but also not totally wrong

The link to the `allure` CLI is broken too (there is no longer a `2.0` page it seems)

> https://docs.qameta.io/allure/2.0/#_commandline

https://docs.qameta.io/allure/ still works, maybe it should just be updated to that?

**Comment by baev** [comment]
Documentation is open-sourced, by the way. See https://github.com/allure-framework/allure-docs

All contributions are welcome.
