### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by anshitbansal21** [allure-framework/allure-npm#38]
Hey everyone, I am a new developer and wanted to contribute to this package. 
Probably a naive question but I wanted to understand how we create the dist folder which contains the code in the `npm` package for this repo.
Basically I have a feeling that the changes I want to introduce are to be done in the .jar files of `/allure-commandline/dist/lib/`. I am unable to find the source code for the same. Can anyone please help me?

**Comment by nixel2007** [comment]
You probably look for https://github.com/allure-framework/allure2
