### ISSUE TITLE
Do not use Java

### ISSUE THREAD

**Issue by grybykm** [allure-framework/allure-npm#39]
Hello,

Is it possible to implement the `allure-commandline` in a way it won't require Java?

Thanks

**Comment by nixel2007** [comment]
Whole allure built on Java, so the short answer is probably no. But you can try to rewrite it from scratch

**Comment by baev** [comment]
Allure 3 is planned to be pure TypeScript. Besides, there are plans to provide native distribution for Allure 2, so stay tuned for the updates.

**Comment by grybykm** [comment]
Wow, that's amazing news! Thank you!
