### ISSUE TITLE
--clean command doesn't clean outputFolder "allure-results"

### ISSUE THREAD

**Issue by elvisduric** [allure-framework/allure-npm#40]
Hi,

I noticed that `allure generate allure-results --clean` won't delete the previous files from the output folder for allure results. This will make many old files confusing after each playwright test run.

Substeps:
1. Run all playwright tests `npx playwright test`
2. Execute again allure cli to clean and generate new report
3. Open allure report `allure open allure-report` -- It shows all tests, i.e. 10 test cases
4. Run specific playwright test `npx playwright test -g 'Test Case X' `
5. Execute allure cli to clean and generate a report `allure generate ./allure-results --clean`
6. Open allure report `allure open allure-report` -- it shows again results for all 10 test cases, although we run only one

Result obtained: The allure-results folder is not accordingly updated with the last test run.
```[tasklist]
### Tasks
```

**Comment by baev** [comment]
The `--clean` command isn't supposed to clean the `allure-results` directory; it's used to remove the report output directory if it exists.

If you want to remove previous results, add a pretest script to remove the `allure-results` directory.
