### ISSUE TITLE
Use a local directory to store binary files

### ISSUE THREAD

**Issue by monolithed** [allure-framework/allure-npm#7]
It's important to prevent blocking by Роскомнадзор and other Github problems

**Comment by just-boris** [comment]
Could you explain your problem?

Binary files are downloaded before publishing and NPM package contains them inside. Whenever you are able to access NPM or some of its mirrors you will get everything that you need.

Also, you can check out actual module content there: https://unpkg.com/allure-commandline@1.5.0/dist/lib/

**Comment by monolithed** [comment]
Hm, got it
