### ISSUE TITLE
The number of step in *.feature

### ISSUE THREAD

**Issue by IlgizVafin** [allure-framework/allure-npm#9]
Hello!

The new version allure-report does not have numbers of step in the test scenario (*.feature). I want to sort the steps in the order in which they are performed.

Please, look at the screen-shot:
![image](https://user-images.githubusercontent.com/7014659/27869826-8ff61a46-61ba-11e7-93a0-338290cf3781.png)

My package.json:
```
"dependencies": {
    "babel-preset-es2015": "~6.24.0",
    "babel-register": "~6.24.0",
    "chai": "~4.0.0",
    "cucumber": "~2.2.0",
    "wdio-cucumber-framework": "~0.3.0",
    "wdio-selenium-standalone-service": "~0.0.8",
    "wdio-spec-reporter": "~0.1.0",
    "webdriverio": "~4.8.0"
},
"devDependencies": {
    "allure-commandline": "^2.1.1",
    "babel-jest": "~20.0.0",
    "babel-polyfill": "~6.23.0",
    "eslint-config-airbnb-base": "~11.2.0",
    "eslint-plugin-import": "~2.6.0",
    "wdio-allure-reporter": "^0.1.2"
}```

**Comment by baev** [comment]
duplicate https://github.com/allure-framework/allure2/issues/403
